// <auto-generated />
using System;
using FBMMultiMessenger.Data.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FBMMultiMessenger.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260110122440_IndexOnFbTimeStamp")]
    partial class IndexOnFbTimeStamp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthStatus")
                        .HasColumnType("integer");

                    b.Property<int>("ConnectionStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Cookie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DefaultMessageId")
                        .HasColumnType("integer");

                    b.Property<string>("FbAccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("LocalServerId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProxyId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DefaultMessageId");

                    b.HasIndex("LocalServerId");

                    b.HasIndex("ProxyId");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("FBChatId")
                        .HasColumnType("text");

                    b.Property<string>("FBListingImage")
                        .HasColumnType("text");

                    b.Property<string>("FbAccountId")
                        .HasColumnType("text");

                    b.Property<string>("FbListingId")
                        .HasColumnType("text");

                    b.Property<string>("FbListingLocation")
                        .HasColumnType("text");

                    b.Property<decimal?>("FbListingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("FbListingTitle")
                        .HasColumnType("text");

                    b.Property<string>("FbUserId")
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("OtherUserId")
                        .HasColumnType("text");

                    b.Property<string>("OtherUserName")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserProfileImage")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("UserId");

                    b.HasIndex("FBChatId", "UserId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.ChatMessages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("FBTimestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("FbMessageId")
                        .HasColumnType("text");

                    b.Property<bool>("IsAudioMessage")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsImageMessage")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReceived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTextMessage")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVideoMessage")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("FBTimestamp");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.ContactUs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReplied")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RepliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Subject")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ContactUs");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.DefaultMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DefaultMessages");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.LocalServer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveBrowserCount")
                        .HasColumnType("integer");

                    b.Property<int>("CoreCount")
                        .HasColumnType("integer");

                    b.Property<string>("CpuArchitecture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CpuThreadCount")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentClockSpeedMHz")
                        .HasColumnType("integer");

                    b.Property<string>("GraphicsCards")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasSSD")
                        .HasColumnType("boolean");

                    b.Property<bool>("Is64BitOS")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSuperServer")
                        .HasColumnType("boolean");

                    b.Property<int>("LogicalProcessors")
                        .HasColumnType("integer");

                    b.Property<int>("MaxBrowserCapacity")
                        .HasColumnType("integer");

                    b.Property<int>("MaxClockSpeedMHz")
                        .HasColumnType("integer");

                    b.Property<string>("MotherboardSerial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProcessorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProcessorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SystemUUID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalMemoryGB")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalStorageGB")
                        .HasColumnType("double precision");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LocalServers");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.PaymentVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountsPurchased")
                        .HasColumnType("integer");

                    b.Property<decimal>("ActualPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HandledByUserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PurchasePrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RejectionReason")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SubmissionNote")
                        .HasColumnType("text");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HandledByUserId");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentVerifications");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.PaymentVerificationImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaymentVerificationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PaymentVerificationId");

                    b.ToTable("PaymentVerificationImages");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.PricingTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxAccounts")
                        .HasColumnType("integer");

                    b.Property<int>("MinAccounts")
                        .HasColumnType("integer");

                    b.Property<decimal>("PricePerAccount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("PricingTiers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxAccounts = 10,
                            MinAccounts = 1,
                            PricePerAccount = 100m
                        },
                        new
                        {
                            Id = 2,
                            MaxAccounts = 20,
                            MinAccounts = 11,
                            PricePerAccount = 50m
                        },
                        new
                        {
                            Id = 3,
                            MaxAccounts = 100,
                            MinAccounts = 21,
                            PricePerAccount = 40m
                        },
                        new
                        {
                            Id = 4,
                            MaxAccounts = 2147483647,
                            MinAccounts = 101,
                            PricePerAccount = 30m
                        });
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.Proxy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ip_Port")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Proxies");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Customer"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "SuperServer"
                        });
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Extension_Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("CanRunOnOurServer")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LimitUsed")
                        .HasColumnType("integer");

                    b.Property<int>("MaxLimit")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanRunOnOurServer = false,
                            ExpiredAt = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LimitUsed = 0,
                            MaxLimit = 100,
                            StartedAt = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CanRunOnOurServer = false,
                            ExpiredAt = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LimitUsed = 0,
                            MaxLimit = 100,
                            StartedAt = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CanRunOnOurServer = false,
                            ExpiredAt = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LimitUsed = 0,
                            MaxLimit = 50,
                            StartedAt = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CanRunOnOurServer = false,
                            ExpiredAt = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LimitUsed = 0,
                            MaxLimit = 50,
                            StartedAt = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CanRunOnOurServer = false,
                            ExpiredAt = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            LimitUsed = 0,
                            MaxLimit = 1000,
                            StartedAt = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 5
                        });
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContactNumber = "03330337272",
                            CreatedAt = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "zbrkhakwani@gmail.com",
                            IsActive = true,
                            IsEmailVerified = false,
                            Name = "Zubair Khakwani",
                            Password = "Zubair!",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 2,
                            ContactNumber = "03330337272",
                            CreatedAt = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "shaheersk12@gmail.com",
                            IsActive = true,
                            IsEmailVerified = false,
                            Name = "Shaheer Khawjikzai",
                            Password = "Shaheer1!",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 3,
                            ContactNumber = "03330337272",
                            CreatedAt = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "test@gmail.com",
                            IsActive = true,
                            IsEmailVerified = false,
                            Name = "Test_Customer",
                            Password = "Test1!",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            ContactNumber = "03330337272",
                            CreatedAt = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@gmail.com",
                            IsActive = true,
                            IsEmailVerified = false,
                            Name = "Test_Admin",
                            Password = "Admin1!",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 5,
                            ContactNumber = "03330337272",
                            CreatedAt = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "super@gmail.com",
                            IsActive = true,
                            IsEmailVerified = false,
                            Name = "Super_Server",
                            Password = "Super1!",
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.VerificationToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEmailVerification")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Otp")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("VerificationTokens");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.Account", b =>
                {
                    b.HasOne("FBMMultiMessenger.Data.Database.DbModels.DefaultMessage", "DefaultMessage")
                        .WithMany("Accounts")
                        .HasForeignKey("DefaultMessageId");

                    b.HasOne("FBMMultiMessenger.Data.Database.DbModels.LocalServer", "LocalServer")
                        .WithMany("Accounts")
                        .HasForeignKey("LocalServerId");

                    b.HasOne("FBMMultiMessenger.Data.Database.DbModels.Proxy", "Proxy")
                        .WithMany("Accounts")
                        .HasForeignKey("ProxyId");

                    b.HasOne("FBMMultiMessenger.Data.Database.DbModels.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefaultMessage");

                    b.Navigation("LocalServer");

                    b.Navigation("Proxy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.Chat", b =>
                {
                    b.HasOne("FBMMultiMessenger.Data.Database.DbModels.Account", "Account")
                        .WithMany("Chats")
                        .HasForeignKey("AccountId");

                    b.HasOne("FBMMultiMessenger.Data.Database.DbModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.ChatMessages", b =>
                {
                    b.HasOne("FBMMultiMessenger.Data.Database.DbModels.Chat", "Chat")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.DefaultMessage", b =>
                {
                    b.HasOne("FBMMultiMessenger.Data.Database.DbModels.User", "User")
                        .WithMany("DefaultMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.LocalServer", b =>
                {
                    b.HasOne("FBMMultiMessenger.Data.Database.DbModels.User", "User")
                        .WithMany("LocalServers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.PaymentVerification", b =>
                {
                    b.HasOne("FBMMultiMessenger.Data.Database.DbModels.User", "HandledByUser")
                        .WithMany()
                        .HasForeignKey("HandledByUserId");

                    b.HasOne("FBMMultiMessenger.Data.Database.DbModels.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId");

                    b.HasOne("FBMMultiMessenger.Data.Database.DbModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HandledByUser");

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.PaymentVerificationImage", b =>
                {
                    b.HasOne("FBMMultiMessenger.Data.Database.DbModels.PaymentVerification", "PaymentVerification")
                        .WithMany("PaymentVerificationImages")
                        .HasForeignKey("PaymentVerificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentVerification");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.Proxy", b =>
                {
                    b.HasOne("FBMMultiMessenger.Data.Database.DbModels.User", "User")
                        .WithMany("Proxies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.Subscription", b =>
                {
                    b.HasOne("FBMMultiMessenger.Data.Database.DbModels.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.User", b =>
                {
                    b.HasOne("FBMMultiMessenger.Data.Database.DbModels.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.VerificationToken", b =>
                {
                    b.HasOne("FBMMultiMessenger.Data.Database.DbModels.User", "User")
                        .WithMany("VerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.Account", b =>
                {
                    b.Navigation("Chats");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.Chat", b =>
                {
                    b.Navigation("ChatMessages");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.DefaultMessage", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.LocalServer", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.PaymentVerification", b =>
                {
                    b.Navigation("PaymentVerificationImages");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.Proxy", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("FBMMultiMessenger.Data.Database.DbModels.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("DefaultMessages");

                    b.Navigation("LocalServers");

                    b.Navigation("Proxies");

                    b.Navigation("Subscriptions");

                    b.Navigation("VerificationTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
